name: Trigger Astroport Dapp Build

on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Main Build
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.MAIN_BUILD_URL }}
          method: GET
